### ISSUE TITLE
Select index of gaudi automatically and can not use the available ones

### ISSUE THREAD

**Issue by anti-machinee** [HabanaAI/Model-References#12]
- I set world size = 4, and habana auto selects 4 last ones.
- But I can not use the gaudi index from 0 to 3 in another process
![image](https://user-images.githubusercontent.com/81377071/163561386-6ff17f27-c91f-46c4-9c9f-c2dae4114deb.png)

**Comment by greg-serochi** [comment]
hi @anti-machinee, we're investigating.

**Comment by greg-serochi** [comment]
hi @anti-machinee, please refer our examples here for setting workloads https://github.com/HabanaAI/Model-References/tree/master/TensorFlow/examples/multitask

**Comment by anti-machinee** [comment]
Thank you @greg-serochi

**Comment by greg-serochi** [comment]
hi @anti-machinee can we close this one?

**Comment by anti-machinee** [comment]
Yes I did
