### ISSUE TITLE
Memory of gaudi is occupied fully no mater how many batchsize is

### ISSUE THREAD

**Issue by anti-machinee** [HabanaAI/Model-References#15]
I use batch size = 32 or 64, gaudi is occupied all 32gb/32gb. Is it the mechanism of gaudi and Habana ?
So that 32gb does not mean any thing?

**Comment by greg-serochi** [comment]
in a future release, we are planning to give additional information on the on-card memory usage

**Comment by greg-serochi** [comment]
Hi @anti-machinee we have a new API in our new release to better check these Memory Usage https://docs.habana.ai/en/latest/PyTorch/PyTorch_User_Guide/Python_Packages.html#memory-stats-apis
