### ISSUE TITLE
Missing script and command typo in Model-References/PyTorch/nlp/GPT2/GettingTheDataset.md document

### ISSUE THREAD

**Issue by JoeyTPChou** [HabanaAI/Model-References#16]
1. In **(3) Partition the xz files obtained in step-2 in to three directories** section, all the `mkdir` command is creating `openwebtext-train`. It should be `mkdir openwebtext-valid` and  `mkdir openwebtext-test` for the valid and test datasets.

2. In **(4) In each of the openwebtext-train, openwebtext-valid and openwebtext-test directories, ...** section, we need to untar the `.xz` files first. The command could be changed to, using `openwebtext-train` as an example: `(cd openwebtext-train && find -name "*.xz" -exec tar -xf {} \; && find -name \*.txt -exec sh -c 'cat {} >> train.raw' \;)`

3. In **(6) Tokeninzing openwebtext** section, there is missing `example` directory under `PyTorch/nlp/GPT2/ ` while accessing the `Model-References/PyTorch/nlp/GPT2/examples/roberta/multiprocessing_bpe_encoder.py`. We need to clone the original repo [fairseq](https://github.com/pytorch/fairseq/blob/main/examples/roberta/multiprocessing_bpe_encoder.py) in order to use it.
4. In **(7) Binarizing the train, valid, test gpt2 tokenized files** section, instead of `mkdir /data/OpenWebText_gpt2` we could do `mkdir -p /data/OpenWebText_gpt2`

**Comment by greg-serochi** [comment]
hi @JoeyTPChou, we are reviewing this now.

**Comment by greg-serochi** [comment]
hi @JoeyTPChou, thanks for your feedback here.  We have made updates to the page to address your comments.

**Comment by greg-serochi** [comment]
Hi @JoeyTPChou, can we close this one?

**Comment by JoeyTPChou** [comment]
Yes, didn't aware that I need to close it, thanks for the remind
