### ISSUE TITLE
tensor does not have a device

### ISSUE THREAD

**Issue by anti-machinee** [HabanaAI/Model-References#19]
- Here is my code which raise an error
```
att_map = self.sigmoid(x_spatial)  # bs*1*7*7
x_combine = x_down4 * att_map + x_down4  # bs*512*7*7
x = self.bn2(x_combine)  # bs*512*7*7

```
`RuntimeError: tensor does not have a device`.
- I freeze layer utils the self.bn2, this error is raise (and it shows that BN has problem), I unfreeze all layer, habana works well
- But in CUDA, I also freeze utils self.bn2, it works well
- I try to not use x_combine = x_down4 * att_map + x_down4 and still freeze util self.bn2, habana works
=> I think the problem is because of `x_combine = x_down4 * att_map + x_down4`
- Could you explain why it works in CUDA but habana, and why do not use x_combine .... fix the bug in habana

**Comment by greg-serochi** [comment]
Hi @anti-machinee, two follow up questions 
1. how is this model frozen? 
2. Can you provide some additional code steps to be able to reproduce this?

Note that Habana SynapseAI Software stack and CUDA are not a direct comparison.

**Comment by Alberto-Villarreal** [comment]
Stale issue. No response from customer. Closing it.
