### ISSUE TITLE
Missing run_lazy_mode option in the argparser in PyTorch's Unet example

### ISSUE THREAD

**Issue by JoeyTPChou** [HabanaAI/Model-References#20]
In the [v. Example: Unet3D in Lazy mode, bf16 mixed precision, Batch Size 2, world-size 8](https://github.com/HabanaAI/Model-References/tree/master/PyTorch/computer_vision/segmentation/Unet#multi-hpu-training), the `run_lazy_mode` option is missing. Please check the script [utils/utils.py](https://github.com/HabanaAI/Model-References/blob/master/PyTorch/computer_vision/segmentation/Unet/utils/utils.py)

**Comment by mandy-li** [comment]
Hi @JoeyTPChou , we fixed the issue. Please check.

**Comment by JoeyTPChou** [comment]
Hi @mandy-li, thanks for the quick fix. I saw the `run_lazy_mode` option is removed from the example command line in the README.md. However, they are still in the source code used as a argument without added into the argparser, is that expected?

**Comment by mandy-li** [comment]
@JoeyTPChou  yes, by default, it is true. So you don't need to set it.
