### ISSUE TITLE
load_library issues with custom op

### ISSUE THREAD

**Issue by eladhoffer** [HabanaAI/Model-References#21]
getting "wrong ELF class: ELFCLASS32" when using torch.ops.load_library on file compiled from https://github.com/HabanaAI/Habana_Custom_Kernel

**Comment by zzhang37** [comment]
You can't load the custom kernel library directly. You need to follow
https://github.com/HabanaAI/Model-References/tree/master/TensorFlow/examples/custom_op
to build the custom op so lib from custom kernel lib, and load that custom op lib.
For PT, refer to https://github.com/HabanaAI/Model-References/tree/master/PyTorch/examples/custom_op/custom_relu

**Comment by mandy-li** [comment]
Closing the issue. Please refer to the links @zzhang37 provided above for help
