### ISSUE TITLE
What is the license of the model data you provide?

### ISSUE THREAD

**Issue by jeremiah** [HabanaAI/Model-References#22]
Hi,

I wonder about the licenses for the data that you provide. Having a clear statement of the license would help those who might like to use your model references and lack of clarity around IP might make some folks hesitant. I imagine you might want to use an MIT license like other folks use for data, but I leave it up to you to determine what is best.

**Comment by ssarkar2** [comment]
In general, Habana does not host/provide datasets. It's up to the user to download/acquire the dataset and to verify the license.
Habana is only publishing the models' scripts. We provide license files for each model we release (which can be found in each model's folder)

Are you looking for license information regarding any specific model/data?

**Comment by jeremiah** [comment]
If I remember correctly I was looking at some data for BERT. But if you do not provide datasets then I guess the point is moot. :^)

**Comment by mandy-li** [comment]
Closing the issue.
