### ISSUE TITLE
Syntax Error in Line 61 : unet2d.py

### ISSUE THREAD

**Issue by hitesh-anand** [HabanaAI/Model-References#23]
Hi,
I have been trying to run the unet2d.py on single Gaudi card. I have followed the steps mentioned [here](https://github.com/HabanaAI/Model-References/tree/master/TensorFlow/computer_vision/Unet2D).

I am getting the following error :  File "unet2d.py", line 61
    log_dir = os.path.join(log_dir, f'worker_{hvd.rank()}')
                                                         ^
SyntaxError: invalid syntax

Even when I am not using the --tensorboard_logging, I am getting the same error. 

Can someone help in resolving this issue?
Thanks

**Comment by ssarkar2** [comment]
Are you using python2 or python3? Asking because it complains "invalid syntax" and the line has a "f-string" which is not supported on python2

**Comment by mandy-li** [comment]
@hitesh-anand please re-open if the problem still occurs with Python3.
