### ISSUE TITLE
How to execute pytorch on specific device?

### ISSUE THREAD

**Issue by vuiseng9** [HabanaAI/Model-References#25]
Hello there, I am new to Gaudi devices, I have been trying the toy sample in the repo on AWS DL1. I attempted to map the follow script
```https://github.com/HabanaAI/Model-References/tree/master/PyTorch/examples/computer_vision/hello_world/example.py``` to one of the 8 cards on the instance by using ```HABANA_VISIBLE_DEVICES=3``` or torch.device("hpu:3"). From ```hl-smi```, it is still running on the first card. Wonder how can we run on a device of choice? Thanks.

**Comment by ssarkar2** [comment]
Hi, thanks for posting.

Are you using the `HABANA_VISIBLE_DEVICES` flag in the `docker run` command (as shown [here](https://docs.habana.ai/en/latest/Orchestration/Multiple_Tenants_on_HPU/Multiple_Dockers_each_with_Single_Workload.html?highlight=HABANA_VISIBLE_DEVICES#setting-the-docker-container))?

**Comment by vuiseng9** [comment]
@ssarkar2 I was operating on the host, out of container environment, i.e.
```HABANA_VISIBLE_DEVICES=3 python3 example.py``` or 
in another experiment without setting the environment variable, I add ```:3``` to ```torch.device("hpu")```

**Comment by Alberto-Villarreal** [comment]
Solution to this issue was posted by @ssarkar2. Closing issue.
