### ISSUE TITLE
Habana Gaudi HPUs Training time improvement

### ISSUE THREAD

**Issue by purvang3** [HabanaAI/Model-References#26]
Hi, I am using Habana® Deep Learning Base AMI tensorflow 2.9.1, aws ec2 instance to train Image segmentation model. Training time for same dataset using similar number of Hpus/Gpus and almost similar Hpu/Gpu memory(40GB vs 32GB) taking more training time compared to Nvidia A100. Key modification from Nvidia Gpu training script is using horovod, habana modules and MPI.

Below I have provided script link which also consist command to be run.
```
https://drive.google.com/drive/folders/1Vq5f9lk_jiRlbkcwpqN_ecS3GC4gKO3W?usp=sharing
```
Please let me know if there is any modifications, that I need to make in code to run faster to compare result with other vendors.

Thank you

**Comment by purvang3** [comment]
Also, when above program runs, HPU utilization is very less as shown. but if I increase the batch size, I get OOM error.
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/39809304/191346927-e6cfb5d5-e8dd-48fc-b2d3-cc9dab1114bf.png">

**Comment by ssarkar2** [comment]
Hi @purvang3 
Please refer to the response [here](https://forum.habana.ai/t/habana-gaudi-hpus-training-time-improvement/319)
